# 03. Tuning & Run (Optuna + N_REPEATS 최종 학습)

01에서 만든 FuxiCTR parquet을 사용해 `MODEL`을 튜닝하고, best params로 N_REPEATS번 재학습 뒤
메트릭과 test 예측을 저장한다.

흐름:
1. `DATASET` / `MODEL` / `N_TRIALS` / `N_REPEATS` 스위치만 설정
2. `configs/models/{MODEL}_base.yaml` + `configs/tuning/{MODEL}_search.yaml` 로드
3. Optuna study (SQLite `artifacts/tuning/...` 저장 → 중단/재개 가능)
4. best params로 N_REPEATS번 재학습 → 메트릭 + test 예측 저장
5. 저장된 run 요약 출력

산출물:
- `artifacts/runs/{dataset_id}/{model_id}.model` (FuxiCTR best checkpoint)
- `artifacts/runs/{dataset_id}/{model_id}.metrics.json` / `.params.json`
- `artifacts/predictions/{dataset_id}/{MODEL}/{run_id}/preds.parquet`
- `artifacts/tuning/{dataset_id}/{MODEL}/study.db` (Optuna, 재개 가능)

In [1]:
import sys, json, copy
from pathlib import Path
import pandas as pd

_HERE = Path.cwd()
if str(_HERE) not in sys.path:
    sys.path.insert(0, str(_HERE))
from utils import nb_utils as U
U.add_fuxictr_to_path()

import optuna
print('optuna =', optuna.__version__)

optuna = 4.8.0

## 1. 스위치

다른 실험을 돌리려면 이 셀만 바꾸면 된다.

In [2]:
DATASET_ID = 'AmazonElectronics_x1'   # 01에서 빌드된 dataset_id
MODEL      = 'DIN'                     # configs/models/{MODEL}_base.yaml 에 정의된 이름
N_TRIALS   = 3                        # Optuna trial 수 (smoke test는 3~5)
N_REPEATS  = 2                         # best params로 재학습할 횟수 (seed만 다름)
SEEDS      = [2026, 2027, 2028, 2029, 2030][:N_REPEATS]
TUNE_EPOCHS = 3                        # 튜닝 trial당 epoch (빨리 탐색)

# study DB (SQLite) 위치 — 존재하면 자동 resume
study_dir = U.ARTIFACT_ROOT / 'tuning' / DATASET_ID / MODEL
study_dir.mkdir(parents=True, exist_ok=True)
STUDY_DB = study_dir / 'study.db'
STUDY_NAME = f'{MODEL}__{DATASET_ID}'
print(f'dataset={DATASET_ID}  model={MODEL}  trials={N_TRIALS}  repeats={N_REPEATS}')
print(f'study  = sqlite:///{STUDY_DB}')

dataset=AmazonElectronics_x1  model=DIN  trials=3  repeats=2
study  = sqlite:////NAS/hyunwoong/Hayanmind-project/notebook/artifacts/tuning/AmazonElectronics_x1/DIN/study.db

## 2. Base config + search space 로드

- `load_base_config(MODEL)` → `DIN_base.yaml`의 Base + MODEL 섹션 + 기본값 머지
- `load_search_space(MODEL)` → `DIN_search.yaml` 의 탐색 공간

In [3]:
base_cfg = U.load_base_config(MODEL)
search_space = U.load_search_space(MODEL)

# feature_map이 있어야 data 경로 검증이 가능
fmap = U.load_feature_map(DATASET_ID)
print(f'base_cfg keys (일부): {sorted(base_cfg)[:12]} ...')
print(f'search_space       : {list(search_space)}')
print(f'feature_map labels : {fmap["labels"]}  total_features={fmap["total_features"]}')

base_cfg keys (일부): ['attention_dropout', 'attention_hidden_activations', 'attention_hidden_units', 'attention_output_activation', 'batch_norm', 'batch_size', 'debug_mode', 'din_sequence_field', 'din_target_field', 'din_use_softmax', 'dnn_activations', 'dnn_hidden_units'] ...
search_space       : ['learning_rate', 'embedding_dim', 'dnn_hidden_units', 'net_dropout', 'attention_dropout', 'batch_size']
feature_map labels : ['label']  total_features=236971

## 3. Optuna objective

- 각 trial마다 `{MODEL}_tune_t{trial_number}` 로 `run_training` 호출 (test 예측 저장 X)
- valid AUC를 반환 → Optuna가 maximize
- 실패한 trial은 `optuna.TrialPruned` 로 스킵

⚠️ 튜닝 중에도 checkpoint는 `artifacts/runs/{dataset_id}/` 아래에 쌓이므로,
나중에 정리하려면 `{MODEL}_tune_*` 패턴으로 삭제하면 된다.

In [4]:
def objective(trial: 'optuna.Trial') -> float:
    suggested = U.suggest_from_space(trial, search_space)
    params = copy.deepcopy(base_cfg)
    params.update(suggested)
    params['epochs'] = TUNE_EPOCHS
    params['save_best_only'] = False  # 튜닝 중 checkpoint IO 최소화
    run_id = f'tune_t{trial.number:03d}_s{params.get("seed", 2026)}'
    try:
        summary = U.run_training(
            dataset_id=DATASET_ID,
            model_name=MODEL,
            params=params,
            run_id=run_id,
            save_test_preds=False,
        )
    except Exception as e:
        print(f'[trial {trial.number}] failed: {e!r}')
        raise optuna.TrialPruned() from e
    auc = summary.get('valid_AUC')
    if auc is None:
        raise optuna.TrialPruned()
    print(f'[trial {trial.number}] valid_AUC={auc:.5f}  params={suggested}')
    return float(auc)

study = optuna.create_study(
    study_name=STUDY_NAME,
    storage=f'sqlite:///{STUDY_DB}',
    direction='maximize',
    load_if_exists=True,
)
print(f'study loaded. prior trials = {len(study.trials)}')

[I 2026-04-16 12:11:07,833] Using an existing study with name 'DIN__AmazonElectronics_x1' instead of creating a new one.

study loaded. prior trials = 2

In [5]:
study.optimize(objective, n_trials=N_TRIALS, show_progress_bar=False)
print('\n=== Optuna summary ===')
print('best value  =', study.best_value)
print('best params =', study.best_params)
df_trials = study.trials_dataframe(attrs=('number','value','state','params','datetime_complete'))
df_trials.tail(min(20, len(df_trials)))

2026-04-16 12:11:09,505 P2243158 INFO FuxiCTR version: 2.3.9
2026-04-16 12:11:09,507 P2243158 INFO Run tune_t002_s2026: {
    "attention_dropout": "0.06185307020001543",
    "attention_hidden_activations": "Dice",
    "attention_hidden_units": "[64]",
    "attention_output_activation": "None",
    "batch_norm": "False",
    "batch_size": "8192",
    "data_format": "parquet",
    "data_root": "/NAS/hyunwoong/Hayanmind-project/data",
    "dataset_id": "AmazonElectronics_x1",
    "debug_mode": "False",
    "din_sequence_field": "[('item_history', 'cate_history')]",
    "din_target_field": "[('item_id', 'cate_id')]",
    "din_use_softmax": "False",
    "dnn_activations": "relu",
    "dnn_hidden_units": "[256, 128]",
    "early_stop_patience": "2",
    "embedding_dim": "64",
    "embedding_regularizer": "0",
    "epochs": "3",
    "eval_steps": "None",
    "feature_config": "None",
    "feature_specs": "[{'name': 'item_history', 'feature_encoder': None}, {'name': 'cate_history', 'feature_encoder': None}]",
    "gpu": "0",
    "group_id": "None",
    "learning_rate": "0.002474107864693061",
    "loss": "binary_crossentropy",
    "metrics": "['AUC', 'logloss']",
    "model": "DIN",
    "model_id": "DIN_tune_t002_s2026",
    "model_root": "/NAS/hyunwoong/Hayanmind-project/notebook/artifacts/runs",
    "monitor": "AUC",
    "monitor_mode": "max",
    "net_dropout": "0.3944041720918892",
    "net_regularizer": "0",
    "num_workers": "3",
    "optimizer": "adam",
    "pickle_feature_encoder": "True",
    "save_best_only": "False",
    "seed": "2026",
    "shuffle": "True",
    "task": "binary_classification",
    "test_data": "/NAS/hyunwoong/Hayanmind-project/data/AmazonElectronics_x1/test.parquet",
    "train_data": "/NAS/hyunwoong/Hayanmind-project/data/AmazonElectronics_x1/train.parquet",
    "use_features": "None",
    "valid_data": "/NAS/hyunwoong/Hayanmind-project/data/AmazonElectronics_x1/valid.parquet",
    "verbose": "1"
}
2026-04-16 12:11:09,511 P2243158 INFO Load feature_map from json: /NAS/hyunwoong/Hayanmind-project/data/AmazonElectronics_x1/feature_map.json
2026-04-16 12:11:09,512 P2243158 INFO Set column index...
2026-04-16 12:11:09,514 P2243158 INFO Loading datasets...
2026-04-16 12:11:17,708 P2243158 INFO Train samples: total/2347550, blocks/1
2026-04-16 12:11:18,707 P2243158 INFO Validation samples: total/261214, blocks/1
2026-04-16 12:11:18,709 P2243158 INFO Loading train and validation data done.
2026-04-16 12:11:20,685 P2243158 INFO Total number of parameters: 15314306.
2026-04-16 12:11:20,687 P2243158 INFO Start training: 287 batches/epoch
2026-04-16 12:11:20,689 P2243158 INFO ************ Epoch=1 start ************

 99%|█████████▉| 285/287 [00:16<00:00, 13.24it/s]

2026-04-16 12:11:36,845 P2243158 INFO Train loss: 0.536376
2026-04-16 12:11:36,847 P2243158 INFO Evaluation @epoch 1 - batch 287:

100%|██████████| 32/32 [00:01<00:00, 17.27it/s]

2026-04-16 12:11:38,914 P2243158 INFO [Metrics] AUC: 0.844292

100%|██████████| 287/287 [00:19<00:00, 15.05it/s]

2026-04-16 12:11:39,771 P2243158 INFO ************ Epoch=1 end ************

100%|█████████▉| 286/287 [00:15<00:00, 15.25it/s]

2026-04-16 12:11:55,225 P2243158 INFO Train loss: 0.450252
2026-04-16 12:11:55,227 P2243158 INFO Evaluation @epoch 2 - batch 287:

100%|██████████| 32/32 [00:01<00:00, 16.56it/s]

2026-04-16 12:11:57,368 P2243158 INFO [Metrics] AUC: 0.864903

100%|██████████| 287/287 [00:18<00:00, 15.55it/s]

2026-04-16 12:11:58,238 P2243158 INFO ************ Epoch=2 end ************

 99%|█████████▉| 285/287 [00:14<00:00, 15.90it/s]

2026-04-16 12:12:12,699 P2243158 INFO Train loss: 0.368056
2026-04-16 12:12:12,700 P2243158 INFO Evaluation @epoch 3 - batch 287:

100%|██████████| 32/32 [00:01<00:00, 19.93it/s]

2026-04-16 12:12:14,518 P2243158 INFO [Metrics] AUC: 0.863546
2026-04-16 12:12:14,521 P2243158 INFO Monitor(max)=0.863546 STOP!
2026-04-16 12:12:14,523 P2243158 INFO Reduce learning rate on plateau: 0.000247

100%|██████████| 287/287 [00:17<00:00, 16.78it/s]

2026-04-16 12:12:15,355 P2243158 INFO ************ Epoch=3 end ************
2026-04-16 12:12:15,356 P2243158 INFO Training finished.
2026-04-16 12:12:15,357 P2243158 INFO Load best model: /NAS/hyunwoong/Hayanmind-project/notebook/artifacts/runs/AmazonElectronics_x1/DIN_tune_t002_s2026.model

2026-04-16 12:12:15,904 P2243158 INFO *** Validation evaluation (run=tune_t002_s2026) ***

100%|██████████| 32/32 [00:01<00:00, 20.83it/s]

2026-04-16 12:12:17,676 P2243158 INFO [Metrics] AUC: 0.863546 - logloss: 0.464459
2026-04-16 12:12:17,680 P2243158 INFO *** Test evaluation (run=tune_t002_s2026) ***
2026-04-16 12:12:17,681 P2243158 INFO Loading datasets...
2026-04-16 12:12:19,021 P2243158 INFO Test samples: total/384806, blocks/1
2026-04-16 12:12:19,023 P2243158 INFO Loading test data done.

100%|██████████| 47/47 [00:02<00:00, 20.22it/s]

2026-04-16 12:12:21,638 P2243158 INFO [Metrics] AUC: 0.849563 - logloss: 0.512983

[run tune_t002_s2026] valid=OrderedDict([('AUC', 0.8635455267152676), ('logloss', 0.4644590608818837)])  test=OrderedDict([('AUC', 0.8495625843596843), ('logloss', 0.5129825288567342)])
[run tune_t002_s2026] artifacts -> /NAS/hyunwoong/Hayanmind-project/notebook/artifacts/runs/AmazonElectronics_x1/DIN_tune_t002_s2026.*
[trial 2] valid_AUC=0.86355  params={'learning_rate': 0.002474107864693061, 'embedding_dim': 64, 'dnn_hidden_units': [256, 128], 'net_dropout': 0.3944041720918892, 'attention_dropout': 0.06185307020001543, 'batch_size': 8192}

[I 2026-04-16 12:12:21,724] Trial 2 finished with value: 0.8635455267152676 and parameters: {'learning_rate': 0.002474107864693061, 'embedding_dim': 64, 'dnn_hidden_units': '[256, 128]', 'net_dropout': 0.3944041720918892, 'attention_dropout': 0.06185307020001543, 'batch_size': 8192}. Best is trial 2 with value: 0.8635455267152676.
2026-04-16 12:12:21,854 P2243158 INFO FuxiCTR version: 2.3.9
2026-04-16 12:12:21,855 P2243158 INFO Run tune_t003_s2026: {
    "attention_dropout": "0.05355988685592915",
    "attention_hidden_activations": "Dice",
    "attention_hidden_units": "[64]",
    "attention_output_activation": "None",
    "batch_norm": "False",
    "batch_size": "2048",
    "data_format": "parquet",
    "data_root": "/NAS/hyunwoong/Hayanmind-project/data",
    "dataset_id": "AmazonElectronics_x1",
    "debug_mode": "False",
    "din_sequence_field": "[('item_history', 'cate_history')]",
    "din_target_field": "[('item_id', 'cate_id')]",
    "din_use_softmax": "False",
    "dnn_activations": "relu",
    "dnn_hidden_units": "[256, 128]",
    "early_stop_patience": "2",
    "embedding_dim": "32",
    "embedding_regularizer": "0",
    "epochs": "3",
    "eval_steps": "None",
    "feature_config": "None",
    "feature_specs": "[{'name': 'item_history', 'feature_encoder': None}, {'name': 'cate_history', 'feature_encoder': None}]",
    "gpu": "0",
    "group_id": "None",
    "learning_rate": "0.0022847348209050146",
    "loss": "binary_crossentropy",
    "metrics": "['AUC', 'logloss']",
    "model": "DIN",
    "model_id": "DIN_tune_t003_s2026",
    "model_root": "/NAS/hyunwoong/Hayanmind-project/notebook/artifacts/runs",
    "monitor": "AUC",
    "monitor_mode": "max",
    "net_dropout": "0.08512909878206293",
    "net_regularizer": "0",
    "num_workers": "3",
    "optimizer": "adam",
    "pickle_feature_encoder": "True",
    "save_best_only": "False",
    "seed": "2026",
    "shuffle": "True",
    "task": "binary_classification",
    "test_data": "/NAS/hyunwoong/Hayanmind-project/data/AmazonElectronics_x1/test.parquet",
    "train_data": "/NAS/hyunwoong/Hayanmind-project/data/AmazonElectronics_x1/train.parquet",
    "use_features": "None",
    "valid_data": "/NAS/hyunwoong/Hayanmind-project/data/AmazonElectronics_x1/valid.parquet",
    "verbose": "1"
}
2026-04-16 12:12:21,859 P2243158 INFO Load feature_map from json: /NAS/hyunwoong/Hayanmind-project/data/AmazonElectronics_x1/feature_map.json
2026-04-16 12:12:21,860 P2243158 INFO Set column index...
2026-04-16 12:12:21,861 P2243158 INFO Loading datasets...
2026-04-16 12:12:28,895 P2243158 INFO Train samples: total/2347550, blocks/1
2026-04-16 12:12:29,975 P2243158 INFO Validation samples: total/261214, blocks/1
2026-04-16 12:12:29,976 P2243158 INFO Loading train and validation data done.
2026-04-16 12:12:30,085 P2243158 INFO Total number of parameters: 7673890.
2026-04-16 12:12:30,087 P2243158 INFO Start training: 1147 batches/epoch
2026-04-16 12:12:30,089 P2243158 INFO ************ Epoch=1 start ************

100%|█████████▉| 1146/1147 [00:22<00:00, 33.90it/s]

2026-04-16 12:12:52,982 P2243158 INFO Train loss: 0.516046
2026-04-16 12:12:52,984 P2243158 INFO Evaluation @epoch 1 - batch 1147:

100%|██████████| 128/128 [00:03<00:00, 41.09it/s]

2026-04-16 12:12:56,326 P2243158 INFO [Metrics] AUC: 0.854924

100%|██████████| 1147/1147 [00:26<00:00, 42.66it/s]

2026-04-16 12:12:56,986 P2243158 INFO ************ Epoch=1 end ************

100%|█████████▉| 1142/1147 [00:22<00:00, 58.30it/s]

2026-04-16 12:13:19,268 P2243158 INFO Train loss: 0.421289
2026-04-16 12:13:19,270 P2243158 INFO Evaluation @epoch 2 - batch 1147:

100%|██████████| 128/128 [00:02<00:00, 49.88it/s]

2026-04-16 12:13:22,042 P2243158 INFO [Metrics] AUC: 0.865988

100%|██████████| 1147/1147 [00:25<00:00, 44.75it/s]

2026-04-16 12:13:22,629 P2243158 INFO ************ Epoch=2 end ************

100%|█████████▉| 1143/1147 [00:19<00:00, 57.44it/s]

2026-04-16 12:13:42,753 P2243158 INFO Train loss: 0.297359
2026-04-16 12:13:42,755 P2243158 INFO Evaluation @epoch 3 - batch 1147:

100%|██████████| 128/128 [00:02<00:00, 48.93it/s]

2026-04-16 12:13:45,576 P2243158 INFO [Metrics] AUC: 0.857037
2026-04-16 12:13:45,579 P2243158 INFO Monitor(max)=0.857037 STOP!
2026-04-16 12:13:45,580 P2243158 INFO Reduce learning rate on plateau: 0.000228

100%|██████████| 1147/1147 [00:23<00:00, 48.75it/s]

2026-04-16 12:13:46,168 P2243158 INFO ************ Epoch=3 end ************
2026-04-16 12:13:46,169 P2243158 INFO Training finished.
2026-04-16 12:13:46,171 P2243158 INFO Load best model: /NAS/hyunwoong/Hayanmind-project/notebook/artifacts/runs/AmazonElectronics_x1/DIN_tune_t003_s2026.model

2026-04-16 12:13:46,447 P2243158 INFO *** Validation evaluation (run=tune_t003_s2026) ***

100%|██████████| 128/128 [00:02<00:00, 46.76it/s]

2026-04-16 12:13:49,411 P2243158 INFO [Metrics] AUC: 0.857037 - logloss: 0.474442
2026-04-16 12:13:49,413 P2243158 INFO *** Test evaluation (run=tune_t003_s2026) ***
2026-04-16 12:13:49,414 P2243158 INFO Loading datasets...
2026-04-16 12:13:50,651 P2243158 INFO Test samples: total/384806, blocks/1
2026-04-16 12:13:50,653 P2243158 INFO Loading test data done.

100%|██████████| 188/188 [00:03<00:00, 52.90it/s]

2026-04-16 12:13:54,484 P2243158 INFO [Metrics] AUC: 0.834420 - logloss: 0.578799
[I 2026-04-16 12:13:54,544] Trial 3 finished with value: 0.8570371857309995 and parameters: {'learning_rate': 0.0022847348209050146, 'embedding_dim': 32, 'dnn_hidden_units': '[256, 128]', 'net_dropout': 0.08512909878206293, 'attention_dropout': 0.05355988685592915, 'batch_size': 2048}. Best is trial 2 with value: 0.8635455267152676.

[run tune_t003_s2026] valid=OrderedDict([('AUC', 0.8570371857309995), ('logloss', 0.47444222591110885)])  test=OrderedDict([('AUC', 0.8344199601377349), ('logloss', 0.5787986609420948)])
[run tune_t003_s2026] artifacts -> /NAS/hyunwoong/Hayanmind-project/notebook/artifacts/runs/AmazonElectronics_x1/DIN_tune_t003_s2026.*
[trial 3] valid_AUC=0.85704  params={'learning_rate': 0.0022847348209050146, 'embedding_dim': 32, 'dnn_hidden_units': [256, 128], 'net_dropout': 0.08512909878206293, 'attention_dropout': 0.05355988685592915, 'batch_size': 2048}

2026-04-16 12:13:54,690 P2243158 INFO FuxiCTR version: 2.3.9
2026-04-16 12:13:54,691 P2243158 INFO Run tune_t004_s2026: {
    "attention_dropout": "0.2531238078843239",
    "attention_hidden_activations": "Dice",
    "attention_hidden_units": "[64]",
    "attention_output_activation": "None",
    "batch_norm": "False",
    "batch_size": "2048",
    "data_format": "parquet",
    "data_root": "/NAS/hyunwoong/Hayanmind-project/data",
    "dataset_id": "AmazonElectronics_x1",
    "debug_mode": "False",
    "din_sequence_field": "[('item_history', 'cate_history')]",
    "din_target_field": "[('item_id', 'cate_id')]",
    "din_use_softmax": "False",
    "dnn_activations": "relu",
    "dnn_hidden_units": "[1024, 512, 256]",
    "early_stop_patience": "2",
    "embedding_dim": "32",
    "embedding_regularizer": "0",
    "epochs": "3",
    "eval_steps": "None",
    "feature_config": "None",
    "feature_specs": "[{'name': 'item_history', 'feature_encoder': None}, {'name': 'cate_history', 'feature_encoder': None}]",
    "gpu": "0",
    "group_id": "None",
    "learning_rate": "0.0004029788665423237",
    "loss": "binary_crossentropy",
    "metrics": "['AUC', 'logloss']",
    "model": "DIN",
    "model_id": "DIN_tune_t004_s2026",
    "model_root": "/NAS/hyunwoong/Hayanmind-project/notebook/artifacts/runs",
    "monitor": "AUC",
    "monitor_mode": "max",
    "net_dropout": "0.2779865882586993",
    "net_regularizer": "0",
    "num_workers": "3",
    "optimizer": "adam",
    "pickle_feature_encoder": "True",
    "save_best_only": "False",
    "seed": "2026",
    "shuffle": "True",
    "task": "binary_classification",
    "test_data": "/NAS/hyunwoong/Hayanmind-project/data/AmazonElectronics_x1/test.parquet",
    "train_data": "/NAS/hyunwoong/Hayanmind-project/data/AmazonElectronics_x1/train.parquet",
    "use_features": "None",
    "valid_data": "/NAS/hyunwoong/Hayanmind-project/data/AmazonElectronics_x1/valid.parquet",
    "verbose": "1"
}
2026-04-16 12:13:54,694 P2243158 INFO Load feature_map from json: /NAS/hyunwoong/Hayanmind-project/data/AmazonElectronics_x1/feature_map.json
2026-04-16 12:13:54,696 P2243158 INFO Set column index...
2026-04-16 12:13:54,696 P2243158 INFO Loading datasets...
2026-04-16 12:14:01,545 P2243158 INFO Train samples: total/2347550, blocks/1
2026-04-16 12:14:02,855 P2243158 INFO Validation samples: total/261214, blocks/1
2026-04-16 12:14:02,857 P2243158 INFO Loading train and validation data done.
2026-04-16 12:14:02,966 P2243158 INFO Total number of parameters: 8420898.
2026-04-16 12:14:02,968 P2243158 INFO Start training: 1147 batches/epoch
2026-04-16 12:14:02,969 P2243158 INFO ************ Epoch=1 start ************

100%|█████████▉| 1142/1147 [00:20<00:00, 58.49it/s]

2026-04-16 12:14:23,391 P2243158 INFO Train loss: 0.528396
2026-04-16 12:14:23,392 P2243158 INFO Evaluation @epoch 1 - batch 1147:

100%|██████████| 128/128 [00:02<00:00, 42.68it/s]

2026-04-16 12:14:26,589 P2243158 INFO [Metrics] AUC: 0.848641

100%|██████████| 1147/1147 [00:24<00:00, 47.26it/s]

2026-04-16 12:14:27,246 P2243158 INFO ************ Epoch=1 end ************

100%|█████████▉| 1142/1147 [00:20<00:00, 61.71it/s]

2026-04-16 12:14:48,066 P2243158 INFO Train loss: 0.439375
2026-04-16 12:14:48,068 P2243158 INFO Evaluation @epoch 2 - batch 1147:

100%|██████████| 128/128 [00:02<00:00, 43.93it/s]

2026-04-16 12:14:51,192 P2243158 INFO [Metrics] AUC: 0.860974

100%|██████████| 1147/1147 [00:24<00:00, 46.70it/s]

2026-04-16 12:14:51,814 P2243158 INFO ************ Epoch=2 end ************

100%|█████████▉| 1145/1147 [00:20<00:00, 37.86it/s]

2026-04-16 12:15:12,620 P2243158 INFO Train loss: 0.326238
2026-04-16 12:15:12,622 P2243158 INFO Evaluation @epoch 3 - batch 1147:

100%|██████████| 128/128 [00:02<00:00, 48.46it/s]

2026-04-16 12:15:15,466 P2243158 INFO [Metrics] AUC: 0.854014
2026-04-16 12:15:15,468 P2243158 INFO Monitor(max)=0.854014 STOP!
2026-04-16 12:15:15,469 P2243158 INFO Reduce learning rate on plateau: 0.000040

100%|██████████| 1147/1147 [00:24<00:00, 47.14it/s]

2026-04-16 12:15:16,153 P2243158 INFO ************ Epoch=3 end ************
2026-04-16 12:15:16,154 P2243158 INFO Training finished.
2026-04-16 12:15:16,156 P2243158 INFO Load best model: /NAS/hyunwoong/Hayanmind-project/notebook/artifacts/runs/AmazonElectronics_x1/DIN_tune_t004_s2026.model

2026-04-16 12:15:16,458 P2243158 INFO *** Validation evaluation (run=tune_t004_s2026) ***

100%|██████████| 128/128 [00:02<00:00, 46.55it/s]

2026-04-16 12:15:19,434 P2243158 INFO [Metrics] AUC: 0.854014 - logloss: 0.478269
2026-04-16 12:15:19,437 P2243158 INFO *** Test evaluation (run=tune_t004_s2026) ***
2026-04-16 12:15:19,438 P2243158 INFO Loading datasets...
2026-04-16 12:15:21,050 P2243158 INFO Test samples: total/384806, blocks/1
2026-04-16 12:15:21,052 P2243158 INFO Loading test data done.

100%|██████████| 188/188 [00:03<00:00, 57.47it/s]

2026-04-16 12:15:24,612 P2243158 INFO [Metrics] AUC: 0.835699 - logloss: 0.551172
[I 2026-04-16 12:15:24,672] Trial 4 finished with value: 0.8540137399733095 and parameters: {'learning_rate': 0.0004029788665423237, 'embedding_dim': 32, 'dnn_hidden_units': '[1024, 512, 256]', 'net_dropout': 0.2779865882586993, 'attention_dropout': 0.2531238078843239, 'batch_size': 2048}. Best is trial 2 with value: 0.8635455267152676.

[run tune_t004_s2026] valid=OrderedDict([('AUC', 0.8540137399733095), ('logloss', 0.4782685044492419)])  test=OrderedDict([('AUC', 0.8356987260674158), ('logloss', 0.5511715945502569)])
[run tune_t004_s2026] artifacts -> /NAS/hyunwoong/Hayanmind-project/notebook/artifacts/runs/AmazonElectronics_x1/DIN_tune_t004_s2026.*
[trial 4] valid_AUC=0.85401  params={'learning_rate': 0.0004029788665423237, 'embedding_dim': 32, 'dnn_hidden_units': [1024, 512, 256], 'net_dropout': 0.2779865882586993, 'attention_dropout': 0.2531238078843239, 'batch_size': 2048}

=== Optuna summary ===
best value  = 0.8635455267152676
best params = {'learning_rate': 0.002474107864693061, 'embedding_dim': 64, 'dnn_hidden_units': '[256, 128]', 'net_dropout': 0.3944041720918892, 'attention_dropout': 0.06185307020001543, 'batch_size': 8192}

,number,value,state,params_attention_dropout,params_batch_size,params_dnn_hidden_units,params_embedding_dim,params_learning_rate,params_net_dropout,datetime_complete
0,0,0.852111,COMPLETE,0.252576,4096,"[512, 256, 128]",16,0.000255,0.089314,2026-04-16 12:06:57.637472
1,1,0.855176,COMPLETE,0.283607,4096,"[256, 128]",16,0.000506,0.426405,2026-04-16 12:08:02.317216
2,2,0.863546,COMPLETE,0.061853,8192,"[256, 128]",64,0.002474,0.394404,2026-04-16 12:12:21.687139
3,3,0.857037,COMPLETE,0.053560,2048,"[256, 128]",32,0.002285,0.085129,2026-04-16 12:13:54.526782
4,4,0.854014,COMPLETE,0.253124,2048,"[1024, 512, 256]",32,0.000403,0.277987,2026-04-16 12:15:24.655252

## 4. best params로 최종 학습 (N_REPEATS)

seed만 다르게 `N_REPEATS`번 재학습한다. 이때는 `save_test_preds=True` 로
test 예측을 parquet에 저장 → 04 분석 노트북에서 바로 로드 가능.

In [6]:
final_summaries = []
for seed in SEEDS:
    params = copy.deepcopy(base_cfg)
    params.update(U.decode_best_params(study.best_params))
    params['seed'] = seed
    run_id = U.make_run_id(MODEL, DATASET_ID, seed)
    print(f'\n=== FINAL RUN seed={seed}  run_id={run_id} ===')
    summary = U.run_training(
        dataset_id=DATASET_ID,
        model_name=MODEL,
        params=params,
        run_id=run_id,
        save_test_preds=True,
    )
    final_summaries.append(summary)

final_df = pd.DataFrame(final_summaries)
print('\n=== final runs ===')
final_df

2026-04-16 12:15:24,746 P2243158 INFO FuxiCTR version: 2.3.9
2026-04-16 12:15:24,748 P2243158 INFO Run 20260416-121524_DIN_AmazonElectronics_x1_s2026: {
    "attention_dropout": "0.06185307020001543",
    "attention_hidden_activations": "Dice",
    "attention_hidden_units": "[64]",
    "attention_output_activation": "None",
    "batch_norm": "False",
    "batch_size": "8192",
    "data_format": "parquet",
    "data_root": "/NAS/hyunwoong/Hayanmind-project/data",
    "dataset_id": "AmazonElectronics_x1",
    "debug_mode": "False",
    "din_sequence_field": "[('item_history', 'cate_history')]",
    "din_target_field": "[('item_id', 'cate_id')]",
    "din_use_softmax": "False",
    "dnn_activations": "relu",
    "dnn_hidden_units": "[256, 128]",
    "early_stop_patience": "2",
    "embedding_dim": "64",
    "embedding_regularizer": "0",
    "epochs": "20",
    "eval_steps": "None",
    "feature_config": "None",
    "feature_specs": "[{'name': 'item_history', 'feature_encoder': None}, {'name': 'cate_history', 'feature_encoder': None}]",
    "gpu": "0",
    "group_id": "None",
    "learning_rate": "0.002474107864693061",
    "loss": "binary_crossentropy",
    "metrics": "['AUC', 'logloss']",
    "model": "DIN",
    "model_id": "DIN_20260416-121524_DIN_AmazonElectronics_x1_s2026",
    "model_root": "/NAS/hyunwoong/Hayanmind-project/notebook/artifacts/runs",
    "monitor": "AUC",
    "monitor_mode": "max",
    "net_dropout": "0.3944041720918892",
    "net_regularizer": "0",
    "num_workers": "3",
    "optimizer": "adam",
    "pickle_feature_encoder": "True",
    "save_best_only": "True",
    "seed": "2026",
    "shuffle": "True",
    "task": "binary_classification",
    "test_data": "/NAS/hyunwoong/Hayanmind-project/data/AmazonElectronics_x1/test.parquet",
    "train_data": "/NAS/hyunwoong/Hayanmind-project/data/AmazonElectronics_x1/train.parquet",
    "use_features": "None",
    "valid_data": "/NAS/hyunwoong/Hayanmind-project/data/AmazonElectronics_x1/valid.parquet",
    "verbose": "1"
}
2026-04-16 12:15:24,751 P2243158 INFO Load feature_map from json: /NAS/hyunwoong/Hayanmind-project/data/AmazonElectronics_x1/feature_map.json
2026-04-16 12:15:24,752 P2243158 INFO Set column index...
2026-04-16 12:15:24,754 P2243158 INFO Loading datasets...

=== FINAL RUN seed=2026  run_id=20260416-121524_DIN_AmazonElectronics_x1_s2026 ===

2026-04-16 12:15:32,006 P2243158 INFO Train samples: total/2347550, blocks/1
2026-04-16 12:15:33,127 P2243158 INFO Validation samples: total/261214, blocks/1
2026-04-16 12:15:33,129 P2243158 INFO Loading train and validation data done.
2026-04-16 12:15:33,350 P2243158 INFO Total number of parameters: 15314306.
2026-04-16 12:15:33,352 P2243158 INFO Start training: 287 batches/epoch
2026-04-16 12:15:33,353 P2243158 INFO ************ Epoch=1 start ************

100%|█████████▉| 286/287 [00:14<00:00, 15.03it/s]

2026-04-16 12:15:48,049 P2243158 INFO Train loss: 0.536376
2026-04-16 12:15:48,051 P2243158 INFO Evaluation @epoch 1 - batch 287:

100%|██████████| 32/32 [00:02<00:00, 15.89it/s]

2026-04-16 12:15:50,271 P2243158 INFO [Metrics] AUC: 0.844292

2026-04-16 12:15:50,275 P2243158 INFO Save best model: monitor(max)=0.844292

100%|██████████| 287/287 [00:18<00:00, 15.84it/s]

2026-04-16 12:15:51,486 P2243158 INFO ************ Epoch=1 end ************

 99%|█████████▉| 285/287 [00:14<00:00, 15.04it/s]

2026-04-16 12:16:06,546 P2243158 INFO Train loss: 0.450252
2026-04-16 12:16:06,548 P2243158 INFO Evaluation @epoch 2 - batch 287:

100%|██████████| 32/32 [00:02<00:00, 15.17it/s]

2026-04-16 12:16:08,864 P2243158 INFO [Metrics] AUC: 0.864903

2026-04-16 12:16:08,868 P2243158 INFO Save best model: monitor(max)=0.864903

100%|██████████| 287/287 [00:18<00:00, 15.50it/s]

2026-04-16 12:16:10,016 P2243158 INFO ************ Epoch=2 end ************

 99%|█████████▉| 285/287 [00:15<00:00, 13.61it/s]

2026-04-16 12:16:25,553 P2243158 INFO Train loss: 0.368056
2026-04-16 12:16:25,554 P2243158 INFO Evaluation @epoch 3 - batch 287:

100%|██████████| 32/32 [00:02<00:00, 15.34it/s]

2026-04-16 12:16:27,845 P2243158 INFO [Metrics] AUC: 0.863546
2026-04-16 12:16:27,848 P2243158 INFO Monitor(max)=0.863546 STOP!
2026-04-16 12:16:27,849 P2243158 INFO Reduce learning rate on plateau: 0.000247

100%|██████████| 287/287 [00:18<00:00, 15.74it/s]

2026-04-16 12:16:28,257 P2243158 INFO ************ Epoch=3 end ************

 99%|█████████▉| 285/287 [00:14<00:00, 14.63it/s]

2026-04-16 12:16:43,108 P2243158 INFO Train loss: 0.229328
2026-04-16 12:16:43,110 P2243158 INFO Evaluation @epoch 4 - batch 287:

100%|██████████| 32/32 [00:02<00:00, 14.74it/s]

2026-04-16 12:16:45,486 P2243158 INFO [Metrics] AUC: 0.855364

2026-04-16 12:16:45,490 P2243158 INFO Monitor(max)=0.855364 STOP!
2026-04-16 12:16:45,491 P2243158 INFO Reduce learning rate on plateau: 0.000025
2026-04-16 12:16:45,493 P2243158 INFO ********* Epoch=4 early stop *********

100%|█████████▉| 286/287 [00:17<00:00, 16.21it/s]

2026-04-16 12:16:45,913 P2243158 INFO Training finished.
2026-04-16 12:16:45,914 P2243158 INFO Load best model: /NAS/hyunwoong/Hayanmind-project/notebook/artifacts/runs/AmazonElectronics_x1/DIN_20260416-121524_DIN_AmazonElectronics_x1_s2026.model

2026-04-16 12:16:46,458 P2243158 INFO *** Validation evaluation (run=20260416-121524_DIN_AmazonElectronics_x1_s2026) ***

100%|██████████| 32/32 [00:01<00:00, 16.51it/s]

2026-04-16 12:16:48,630 P2243158 INFO [Metrics] AUC: 0.864903 - logloss: 0.460568
2026-04-16 12:16:48,634 P2243158 INFO *** Test evaluation (run=20260416-121524_DIN_AmazonElectronics_x1_s2026) ***
2026-04-16 12:16:48,635 P2243158 INFO Loading datasets...
2026-04-16 12:16:50,148 P2243158 INFO Test samples: total/384806, blocks/1
2026-04-16 12:16:50,150 P2243158 INFO Loading test data done.

100%|██████████| 47/47 [00:02<00:00, 16.49it/s]

2026-04-16 12:16:53,286 P2243158 INFO [Metrics] AUC: 0.852022 - logloss: 0.482683
2026-04-16 12:16:53,290 P2243158 INFO Loading datasets...
2026-04-16 12:16:54,794 P2243158 INFO Test samples: total/384806, blocks/1
2026-04-16 12:16:54,796 P2243158 INFO Loading test data done.

100%|██████████| 47/47 [00:02<00:00, 17.90it/s]

2026-04-16 12:16:59,866 P2243158 INFO FuxiCTR version: 2.3.9
2026-04-16 12:16:59,868 P2243158 INFO Run 20260416-121659_DIN_AmazonElectronics_x1_s2027: {
    "attention_dropout": "0.06185307020001543",
    "attention_hidden_activations": "Dice",
    "attention_hidden_units": "[64]",
    "attention_output_activation": "None",
    "batch_norm": "False",
    "batch_size": "8192",
    "data_format": "parquet",
    "data_root": "/NAS/hyunwoong/Hayanmind-project/data",
    "dataset_id": "AmazonElectronics_x1",
    "debug_mode": "False",
    "din_sequence_field": "[('item_history', 'cate_history')]",
    "din_target_field": "[('item_id', 'cate_id')]",
    "din_use_softmax": "False",
    "dnn_activations": "relu",
    "dnn_hidden_units": "[256, 128]",
    "early_stop_patience": "2",
    "embedding_dim": "64",
    "embedding_regularizer": "0",
    "epochs": "20",
    "eval_steps": "None",
    "feature_config": "None",
    "feature_specs": "[{'name': 'item_history', 'feature_encoder': None}, {'name': 'cate_history', 'feature_encoder': None}]",
    "gpu": "0",
    "group_id": "None",
    "learning_rate": "0.002474107864693061",
    "loss": "binary_crossentropy",
    "metrics": "['AUC', 'logloss']",
    "model": "DIN",
    "model_id": "DIN_20260416-121659_DIN_AmazonElectronics_x1_s2027",
    "model_root": "/NAS/hyunwoong/Hayanmind-project/notebook/artifacts/runs",
    "monitor": "AUC",
    "monitor_mode": "max",
    "net_dropout": "0.3944041720918892",
    "net_regularizer": "0",
    "num_workers": "3",
    "optimizer": "adam",
    "pickle_feature_encoder": "True",
    "save_best_only": "True",
    "seed": "2027",
    "shuffle": "True",
    "task": "binary_classification",
    "test_data": "/NAS/hyunwoong/Hayanmind-project/data/AmazonElectronics_x1/test.parquet",
    "train_data": "/NAS/hyunwoong/Hayanmind-project/data/AmazonElectronics_x1/train.parquet",
    "use_features": "None",
    "valid_data": "/NAS/hyunwoong/Hayanmind-project/data/AmazonElectronics_x1/valid.parquet",
    "verbose": "1"
}
2026-04-16 12:16:59,872 P2243158 INFO Load feature_map from json: /NAS/hyunwoong/Hayanmind-project/data/AmazonElectronics_x1/feature_map.json
2026-04-16 12:16:59,874 P2243158 INFO Set column index...
2026-04-16 12:16:59,876 P2243158 INFO Loading datasets...

[preds] saved 384,806 rows -> /NAS/hyunwoong/Hayanmind-project/notebook/artifacts/predictions/AmazonElectronics_x1/DIN/20260416-121524_DIN_AmazonElectronics_x1_s2026/preds.parquet
[run 20260416-121524_DIN_AmazonElectronics_x1_s2026] valid=OrderedDict([('AUC', 0.864902544757905), ('logloss', 0.4605677430978141)])  test=OrderedDict([('AUC', 0.852021547445265), ('logloss', 0.4826834327906191)])
[run 20260416-121524_DIN_AmazonElectronics_x1_s2026] artifacts -> /NAS/hyunwoong/Hayanmind-project/notebook/artifacts/runs/AmazonElectronics_x1/DIN_20260416-121524_DIN_AmazonElectronics_x1_s2026.*
[run 20260416-121524_DIN_AmazonElectronics_x1_s2026] preds    -> /NAS/hyunwoong/Hayanmind-project/notebook/artifacts/predictions/AmazonElectronics_x1/DIN/20260416-121524_DIN_AmazonElectronics_x1_s2026/preds.parquet

=== FINAL RUN seed=2027  run_id=20260416-121659_DIN_AmazonElectronics_x1_s2027 ===

2026-04-16 12:17:05,206 P2243158 INFO Train samples: total/2347550, blocks/1
2026-04-16 12:17:06,034 P2243158 INFO Validation samples: total/261214, blocks/1
2026-04-16 12:17:06,035 P2243158 INFO Loading train and validation data done.
2026-04-16 12:17:06,237 P2243158 INFO Total number of parameters: 15314306.
2026-04-16 12:17:06,239 P2243158 INFO Start training: 287 batches/epoch
2026-04-16 12:17:06,241 P2243158 INFO ************ Epoch=1 start ************

100%|█████████▉| 286/287 [00:15<00:00, 15.33it/s]

2026-04-16 12:17:21,350 P2243158 INFO Train loss: 0.539401
2026-04-16 12:17:21,352 P2243158 INFO Evaluation @epoch 1 - batch 287:

100%|██████████| 32/32 [00:02<00:00, 15.27it/s]

2026-04-16 12:17:23,647 P2243158 INFO [Metrics] AUC: 0.842728
2026-04-16 12:17:23,650 P2243158 INFO Save best model: monitor(max)=0.842728

100%|██████████| 287/287 [00:18<00:00, 15.26it/s]

2026-04-16 12:17:25,058 P2243158 INFO ************ Epoch=1 end ************

 99%|█████████▉| 284/287 [00:14<00:00, 21.67it/s]

2026-04-16 12:17:39,993 P2243158 INFO Train loss: 0.453889
2026-04-16 12:17:39,995 P2243158 INFO Evaluation @epoch 2 - batch 287:

100%|██████████| 32/32 [00:02<00:00, 13.49it/s]

2026-04-16 12:17:42,571 P2243158 INFO [Metrics] AUC: 0.862744

2026-04-16 12:17:42,578 P2243158 INFO Save best model: monitor(max)=0.862744

100%|██████████| 287/287 [00:18<00:00, 15.45it/s]

2026-04-16 12:17:43,641 P2243158 INFO ************ Epoch=2 end ************

 99%|█████████▉| 284/287 [00:14<00:00, 21.57it/s]

2026-04-16 12:17:58,798 P2243158 INFO Train loss: 0.374307
2026-04-16 12:17:58,800 P2243158 INFO Evaluation @epoch 3 - batch 287:

100%|██████████| 32/32 [00:02<00:00, 12.77it/s]

2026-04-16 12:18:01,510 P2243158 INFO [Metrics] AUC: 0.862924
2026-04-16 12:18:01,514 P2243158 INFO Save best model: monitor(max)=0.862924

100%|██████████| 287/287 [00:19<00:00, 14.78it/s]

2026-04-16 12:18:03,066 P2243158 INFO ************ Epoch=3 end ************

 99%|█████████▉| 284/287 [00:16<00:00, 19.88it/s]

2026-04-16 12:18:19,498 P2243158 INFO Train loss: 0.282701
2026-04-16 12:18:19,502 P2243158 INFO Evaluation @epoch 4 - batch 287:

100%|██████████| 32/32 [00:02<00:00, 11.22it/s]

2026-04-16 12:18:22,631 P2243158 INFO [Metrics] AUC: 0.855084
2026-04-16 12:18:22,636 P2243158 INFO Monitor(max)=0.855084 STOP!
2026-04-16 12:18:22,637 P2243158 INFO Reduce learning rate on plateau: 0.000247

100%|██████████| 287/287 [00:20<00:00, 14.24it/s]

2026-04-16 12:18:23,230 P2243158 INFO ************ Epoch=4 end ************

100%|█████████▉| 286/287 [00:15<00:00, 14.12it/s]

2026-04-16 12:18:38,993 P2243158 INFO Train loss: 0.170201
2026-04-16 12:18:38,995 P2243158 INFO Evaluation @epoch 5 - batch 287:

100%|██████████| 32/32 [00:02<00:00, 11.13it/s]

2026-04-16 12:18:42,096 P2243158 INFO [Metrics] AUC: 0.849740
2026-04-16 12:18:42,100 P2243158 INFO Monitor(max)=0.849740 STOP!
2026-04-16 12:18:42,102 P2243158 INFO Reduce learning rate on plateau: 0.000025
2026-04-16 12:18:42,103 P2243158 INFO ********* Epoch=5 early stop *********

100%|█████████▉| 286/287 [00:19<00:00, 14.67it/s]

2026-04-16 12:18:42,739 P2243158 INFO Training finished.
2026-04-16 12:18:42,741 P2243158 INFO Load best model: /NAS/hyunwoong/Hayanmind-project/notebook/artifacts/runs/AmazonElectronics_x1/DIN_20260416-121659_DIN_AmazonElectronics_x1_s2027.model

2026-04-16 12:18:43,296 P2243158 INFO *** Validation evaluation (run=20260416-121659_DIN_AmazonElectronics_x1_s2027) ***

100%|██████████| 32/32 [00:03<00:00,  9.82it/s]

2026-04-16 12:18:46,812 P2243158 INFO [Metrics] AUC: 0.862924 - logloss: 0.463801
2026-04-16 12:18:46,817 P2243158 INFO *** Test evaluation (run=20260416-121659_DIN_AmazonElectronics_x1_s2027) ***
2026-04-16 12:18:46,819 P2243158 INFO Loading datasets...
2026-04-16 12:18:48,567 P2243158 INFO Test samples: total/384806, blocks/1
2026-04-16 12:18:48,569 P2243158 INFO Loading test data done.

100%|██████████| 47/47 [00:03<00:00, 13.16it/s]

2026-04-16 12:18:52,481 P2243158 INFO [Metrics] AUC: 0.845535 - logloss: 0.520752
2026-04-16 12:18:52,486 P2243158 INFO Loading datasets...
2026-04-16 12:18:54,166 P2243158 INFO Test samples: total/384806, blocks/1
2026-04-16 12:18:54,168 P2243158 INFO Loading test data done.

100%|██████████| 47/47 [00:03<00:00, 13.07it/s]
[preds] saved 384,806 rows -> /NAS/hyunwoong/Hayanmind-project/notebook/artifacts/predictions/AmazonElectronics_x1/DIN/20260416-121659_DIN_AmazonElectronics_x1_s2027/preds.parquet
[run 20260416-121659_DIN_AmazonElectronics_x1_s2027] valid=OrderedDict([('AUC', 0.8629237503448335), ('logloss', 0.46380101073939767)])  test=OrderedDict([('AUC', 0.8455350325829702), ('logloss', 0.5207521291036592)])
[run 20260416-121659_DIN_AmazonElectronics_x1_s2027] artifacts -> /NAS/hyunwoong/Hayanmind-project/notebook/artifacts/runs/AmazonElectronics_x1/DIN_20260416-121659_DIN_AmazonElectronics_x1_s2027.*
[run 20260416-121659_DIN_AmazonElectronics_x1_s2027] preds    -> /NAS/hyunwoong/Hayanmind-project/notebook/artifacts/predictions/AmazonElectronics_x1/DIN/20260416-121659_DIN_AmazonElectronics_x1_s2027/preds.parquet

=== final runs ===

,model,dataset_id,run_id,model_id,train_seconds,valid_AUC,valid_logloss,test_AUC,test_logloss
0,DIN,AmazonElectronics_x1,20260416-121524_DIN_AmazonElectronics_x1_s2026,DIN_20260416-121524_DIN_AmazonElectronics_x1_s...,73.11,0.864903,0.460568,0.852022,0.482683
1,DIN,AmazonElectronics_x1,20260416-121659_DIN_AmazonElectronics_x1_s2027,DIN_20260416-121659_DIN_AmazonElectronics_x1_s...,97.06,0.862924,0.463801,0.845535,0.520752

## 5. 저장된 run 요약 출력 (list_runs)

`artifacts/runs/{DATASET_ID}/` 아래에 쌓인 모든 run(튜닝 trial 포함)을 메트릭 표로.

In [7]:
runs = U.list_runs(DATASET_ID)
cols = [c for c in ['dataset','model','run_id','metric.valid_AUC','metric.test_AUC','metric.valid_logloss','metric.test_logloss','metric.train_seconds'] if c in runs.columns]
runs[cols].sort_values(cols[-2] if 'metric.test_AUC' in cols else 'run_id', ascending=False).head(30)

,dataset,model,run_id,metric.valid_AUC,metric.test_AUC,metric.valid_logloss,metric.test_logloss,metric.train_seconds
5,AmazonElectronics_x1,DIN,tune_t003_s2026,0.857037,0.834420,0.474442,0.578799,76.36
6,AmazonElectronics_x1,DIN,tune_t004_s2026,0.854014,0.835699,0.478269,0.551172,73.49
2,AmazonElectronics_x1,DIN,tune_t000_s2026,0.852111,0.836035,0.478116,0.521070,49.87
1,AmazonElectronics_x1,DIN,20260416-121659_DIN_AmazonElectronics_x1_s2027,0.862924,0.845535,0.463801,0.520752,97.06
4,AmazonElectronics_x1,DIN,tune_t002_s2026,0.863546,0.849563,0.464459,0.512983,55.22
3,AmazonElectronics_x1,DIN,tune_t001_s2026,0.855176,0.839740,0.473655,0.511686,50.13
0,AmazonElectronics_x1,DIN,20260416-121524_DIN_AmazonElectronics_x1_s2026,0.864903,0.852022,0.460568,0.482683,73.11