# 03. Tuning & Run (Optuna + N_REPEATS 최종 학습)

01에서 만든 FuxiCTR parquet을 사용해 `MODEL`을 튜닝하고, best params로 N_REPEATS번 재학습 뒤
메트릭과 test 예측을 저장한다.

흐름:
1. `DATASET` / `MODEL` / `N_TRIALS` / `N_REPEATS` 스위치만 설정
2. `configs/models/{MODEL}_base.yaml` + `configs/tuning/{MODEL}_search.yaml` 로드
3. Optuna study (SQLite `artifacts/tuning/...` 저장 → 중단/재개 가능)
4. best params로 N_REPEATS번 재학습 → 메트릭 + test 예측 저장
5. 저장된 run 요약 출력

산출물:
- `artifacts/runs/{dataset_id}/{model_id}.model` (FuxiCTR best checkpoint)
- `artifacts/runs/{dataset_id}/{model_id}.metrics.json` / `.params.json`
- `artifacts/predictions/{dataset_id}/{MODEL}/{run_id}/preds.parquet`
- `artifacts/tuning/{dataset_id}/{MODEL}/study.db` (Optuna, 재개 가능)

In [1]:
import sys, json, copy
from pathlib import Path
import pandas as pd

_HERE = Path.cwd()
if str(_HERE) not in sys.path:
    sys.path.insert(0, str(_HERE))
from utils import nb_utils as U
U.add_fuxictr_to_path()

import optuna
print('optuna =', optuna.__version__)

optuna = 4.8.0

## 1. 스위치

다른 실험을 돌리려면 이 셀만 바꾸면 된다.

In [2]:
DATASET_ID = 'TAAC2026'   # 01에서 빌드된 dataset_id
MODEL      = 'DIN'                     # configs/models/{MODEL}_base.yaml 에 정의된 이름
N_TRIALS   = 3                        # Optuna trial 수 (smoke test는 3~5)
N_REPEATS  = 2                         # best params로 재학습할 횟수 (seed만 다름)
SEEDS      = [2026, 2027, 2028, 2029, 2030][:N_REPEATS]
TUNE_EPOCHS = 3                        # 튜닝 trial당 epoch (빨리 탐색)

# study DB (SQLite) 위치 — 존재하면 자동 resume
study_dir = U.ARTIFACT_ROOT / 'tuning' / DATASET_ID / MODEL
study_dir.mkdir(parents=True, exist_ok=True)
STUDY_DB = study_dir / 'study.db'
STUDY_NAME = f'{MODEL}__{DATASET_ID}'
print(f'dataset={DATASET_ID}  model={MODEL}  trials={N_TRIALS}  repeats={N_REPEATS}')
print(f'study  = sqlite:///{STUDY_DB}')

dataset=TAAC2026  model=DIN  trials=3  repeats=2
study  = sqlite:////NAS/hyunwoong/Hayanmind-project/notebook/artifacts/tuning/TAAC2026/DIN/study.db

## 2. Base config + search space 로드

- `load_base_config(MODEL, DATASET_ID)` → `{MODEL}_base.yaml`의 defaults → Base → Base@{DATASET_ID} → MODEL → MODEL@{DATASET_ID} 순으로 머지
  (데이터셋별 `feature_specs` / `*_target_field` / `*_sequence_field` 오버라이드가 자동 적용됨)
- `load_search_space(MODEL)` → `{MODEL}_search.yaml` 의 탐색 공간

In [3]:
base_cfg = U.load_base_config(MODEL, DATASET_ID)
search_space = U.load_search_space(MODEL)

# feature_map이 있어야 data 경로 검증이 가능
fmap = U.load_feature_map(DATASET_ID)
print(f'base_cfg keys (일부): {sorted(base_cfg)[:12]} ...')
print(f'search_space       : {list(search_space)}')
print(f'feature_map labels : {fmap["labels"]}  total_features={fmap["total_features"]}')

base_cfg keys (일부): ['attention_dropout', 'attention_hidden_activations', 'attention_hidden_units', 'attention_output_activation', 'batch_norm', 'batch_size', 'debug_mode', 'din_sequence_field', 'din_target_field', 'din_use_softmax', 'dnn_activations', 'dnn_hidden_units'] ...
search_space       : ['learning_rate', 'embedding_dim', 'dnn_hidden_units', 'net_dropout', 'attention_dropout', 'batch_size']
feature_map labels : ['label']  total_features=1530322

## 3. Optuna objective

- 각 trial마다 `{MODEL}_tune_t{trial_number}` 로 `run_training` 호출 (test 예측 저장 X)
- valid AUC를 반환 → Optuna가 maximize
- 실패한 trial은 `optuna.TrialPruned` 로 스킵

⚠️ 튜닝 중에도 checkpoint는 `artifacts/runs/{dataset_id}/` 아래에 쌓이므로,
나중에 정리하려면 `{MODEL}_tune_*` 패턴으로 삭제하면 된다.

In [4]:
def objective(trial: 'optuna.Trial') -> float:
    suggested = U.suggest_from_space(trial, search_space)
    params = copy.deepcopy(base_cfg)
    params.update(suggested)
    params['epochs'] = TUNE_EPOCHS
    params['save_best_only'] = False  # 튜닝 중 checkpoint IO 최소화
    run_id = f'tune_t{trial.number:03d}_s{params.get("seed", 2026)}'
    try:
        summary = U.run_training(
            dataset_id=DATASET_ID,
            model_name=MODEL,
            params=params,
            run_id=run_id,
            save_test_preds=False,
        )
    except Exception as e:
        print(f'[trial {trial.number}] failed: {e!r}')
        raise optuna.TrialPruned() from e
    auc = summary.get('valid_AUC')
    if auc is None:
        raise optuna.TrialPruned()
    print(f'[trial {trial.number}] valid_AUC={auc:.5f}  params={suggested}')
    return float(auc)

study = optuna.create_study(
    study_name=STUDY_NAME,
    storage=f'sqlite:///{STUDY_DB}',
    direction='maximize',
    load_if_exists=True,
)
print(f'study loaded. prior trials = {len(study.trials)}')

[I 2026-04-19 15:29:11,675] A new study created in RDB with name: DIN__TAAC2026

study loaded. prior trials = 0

In [5]:
study.optimize(objective, n_trials=N_TRIALS, show_progress_bar=False)
print('\n=== Optuna summary ===')
print('best value  =', study.best_value)
print('best params =', study.best_params)
df_trials = study.trials_dataframe(attrs=('number','value','state','params','datetime_complete'))
df_trials.tail(min(20, len(df_trials)))

2026-04-19 15:29:13,573 P2399999 INFO FuxiCTR version: 2.3.9
2026-04-19 15:29:13,575 P2399999 INFO Run tune_t000_s2026: {
    "attention_dropout": "0.2150721079075201",
    "attention_hidden_activations": "Dice",
    "attention_hidden_units": "[64]",
    "attention_output_activation": "None",
    "batch_norm": "False",
    "batch_size": "4096",
    "data_format": "parquet",
    "data_root": "/NAS/hyunwoong/Hayanmind-project/data",
    "dataset_id": "TAAC2026",
    "debug_mode": "False",
    "din_sequence_field": "item_int_feats_11",
    "din_target_field": "item_id",
    "din_use_softmax": "False",
    "dnn_activations": "relu",
    "dnn_hidden_units": "[512, 256, 128]",
    "early_stop_patience": "2",
    "embedding_dim": "32",
    "embedding_regularizer": "0",
    "epochs": "3",
    "eval_steps": "None",
    "feature_config": "None",
    "feature_specs": "[{'name': 'item_int_feats_11', 'feature_encoder': None}]",
    "gpu": "0",
    "group_id": "None",
    "learning_rate": "0.0007604734065844932",
    "loss": "binary_crossentropy",
    "metrics": "['AUC', 'logloss']",
    "model": "DIN",
    "model_id": "DIN_tune_t000_s2026",
    "model_root": "/NAS/hyunwoong/Hayanmind-project/notebook/artifacts/runs",
    "monitor": "AUC",
    "monitor_mode": "max",
    "net_dropout": "0.04846728945740564",
    "net_regularizer": "0",
    "num_workers": "3",
    "optimizer": "adam",
    "pickle_feature_encoder": "True",
    "save_best_only": "False",
    "seed": "2026",
    "shuffle": "True",
    "task": "binary_classification",
    "test_data": "/NAS/hyunwoong/Hayanmind-project/data/TAAC2026/test.parquet",
    "train_data": "/NAS/hyunwoong/Hayanmind-project/data/TAAC2026/train.parquet",
    "use_features": "None",
    "valid_data": "/NAS/hyunwoong/Hayanmind-project/data/TAAC2026/valid.parquet",
    "verbose": "1"
}
2026-04-19 15:29:13,581 P2399999 INFO Load feature_map from json: /NAS/hyunwoong/Hayanmind-project/data/TAAC2026/feature_map.json
2026-04-19 15:29:13,584 P2399999 INFO Set column index...
2026-04-19 15:29:13,587 P2399999 INFO Loading datasets...
2026-04-19 15:29:13,740 P2399999 INFO Train samples: total/630, blocks/1
2026-04-19 15:29:13,781 P2399999 INFO Validation samples: total/70, blocks/1
2026-04-19 15:29:13,782 P2399999 INFO Loading train and validation data done.
2026-04-19 15:29:14,792 P2399999 INFO Loading pretrained_emb: /NAS/hyunwoong/Hayanmind-project/data/TAAC2026/pretrained_fid_61.h5
2026-04-19 15:29:15,915 P2399999 INFO Loading pretrained_emb: /NAS/hyunwoong/Hayanmind-project/data/TAAC2026/pretrained_fid_87.h5
2026-04-19 15:29:18,554 P2399999 INFO Total number of parameters: 51076354.
2026-04-19 15:29:18,559 P2399999 INFO Start training: 1 batches/epoch
2026-04-19 15:29:18,560 P2399999 INFO ************ Epoch=1 start ************

  0%|          | 0/1 [00:00<?, ?it/s]

2026-04-19 15:29:19,297 P2399999 INFO Train loss: 13.809524
2026-04-19 15:29:19,300 P2399999 INFO Evaluation @epoch 1 - batch 1:

100%|██████████| 1/1 [00:00<00:00,  4.16it/s]

2026-04-19 15:29:19,563 P2399999 INFO [Metrics] AUC: 0.500000

100%|██████████| 1/1 [00:02<00:00,  2.86s/it]

2026-04-19 15:29:21,441 P2399999 INFO ************ Epoch=1 end ************

  0%|          | 0/1 [00:00<?, ?it/s]

2026-04-19 15:29:21,731 P2399999 INFO Train loss: 14.603175
2026-04-19 15:29:21,735 P2399999 INFO Evaluation @epoch 2 - batch 1:

100%|██████████| 1/1 [00:00<00:00,  4.12it/s]

2026-04-19 15:29:22,000 P2399999 INFO [Metrics] AUC: 0.500000
2026-04-19 15:29:22,006 P2399999 INFO Monitor(max)=0.500000 STOP!
2026-04-19 15:29:22,007 P2399999 INFO Reduce learning rate on plateau: 0.000076

100%|██████████| 1/1 [00:02<00:00,  2.56s/it]

2026-04-19 15:29:24,026 P2399999 INFO ************ Epoch=2 end ************

  0%|          | 0/1 [00:00<?, ?it/s]

2026-04-19 15:29:24,301 P2399999 INFO Train loss: 13.968254
2026-04-19 15:29:24,305 P2399999 INFO Evaluation @epoch 3 - batch 1:

100%|██████████| 1/1 [00:00<00:00,  4.96it/s]

2026-04-19 15:29:24,523 P2399999 INFO [Metrics] AUC: 0.500000
2026-04-19 15:29:24,525 P2399999 INFO Monitor(max)=0.500000 STOP!
2026-04-19 15:29:24,526 P2399999 INFO Reduce learning rate on plateau: 0.000008
2026-04-19 15:29:24,526 P2399999 INFO ********* Epoch=3 early stop *********

  0%|          | 0/1 [00:02<?, ?it/s]

2026-04-19 15:29:26,517 P2399999 INFO Training finished.
2026-04-19 15:29:26,518 P2399999 INFO Load best model: /NAS/hyunwoong/Hayanmind-project/notebook/artifacts/runs/TAAC2026/DIN_tune_t000_s2026.model

2026-04-19 15:29:28,349 P2399999 INFO *** Validation evaluation (run=tune_t000_s2026) ***

100%|██████████| 1/1 [00:00<00:00,  4.18it/s]

2026-04-19 15:29:28,611 P2399999 INFO [Metrics] AUC: 0.500000 - logloss: 2.302585
2026-04-19 15:29:28,615 P2399999 INFO *** Test evaluation (run=tune_t000_s2026) ***
2026-04-19 15:29:28,617 P2399999 INFO Loading datasets...
2026-04-19 15:29:28,710 P2399999 INFO Test samples: total/300, blocks/1
2026-04-19 15:29:28,711 P2399999 INFO Loading test data done.

100%|██████████| 1/1 [00:00<00:00,  3.73it/s]

2026-04-19 15:29:28,999 P2399999 INFO [Metrics] AUC: 0.500000 - logloss: 1.987899
[I 2026-04-19 15:29:29,092] Trial 0 finished with value: 0.5 and parameters: {'learning_rate': 0.0007604734065844932, 'embedding_dim': 32, 'dnn_hidden_units': '[512, 256, 128]', 'net_dropout': 0.04846728945740564, 'attention_dropout': 0.2150721079075201, 'batch_size': 4096}. Best is trial 0 with value: 0.5.

[run tune_t000_s2026] valid=OrderedDict([('AUC', 0.5), ('logloss', 2.302585178708335)])  test=OrderedDict([('AUC', 0.5), ('logloss', 1.9878985512848644)])
[run tune_t000_s2026] artifacts -> /NAS/hyunwoong/Hayanmind-project/notebook/artifacts/runs/TAAC2026/DIN_tune_t000_s2026.*
[trial 0] valid_AUC=0.50000  params={'learning_rate': 0.0007604734065844932, 'embedding_dim': 32, 'dnn_hidden_units': [512, 256, 128], 'net_dropout': 0.04846728945740564, 'attention_dropout': 0.2150721079075201, 'batch_size': 4096}

2026-04-19 15:29:29,234 P2399999 INFO FuxiCTR version: 2.3.9
2026-04-19 15:29:29,236 P2399999 INFO Run tune_t001_s2026: {
    "attention_dropout": "0.2533409855578874",
    "attention_hidden_activations": "Dice",
    "attention_hidden_units": "[64]",
    "attention_output_activation": "None",
    "batch_norm": "False",
    "batch_size": "4096",
    "data_format": "parquet",
    "data_root": "/NAS/hyunwoong/Hayanmind-project/data",
    "dataset_id": "TAAC2026",
    "debug_mode": "False",
    "din_sequence_field": "item_int_feats_11",
    "din_target_field": "item_id",
    "din_use_softmax": "False",
    "dnn_activations": "relu",
    "dnn_hidden_units": "[512, 256, 128]",
    "early_stop_patience": "2",
    "embedding_dim": "32",
    "embedding_regularizer": "0",
    "epochs": "3",
    "eval_steps": "None",
    "feature_config": "None",
    "feature_specs": "[{'name': 'item_int_feats_11', 'feature_encoder': None}]",
    "gpu": "0",
    "group_id": "None",
    "learning_rate": "0.000780037276846175",
    "loss": "binary_crossentropy",
    "metrics": "['AUC', 'logloss']",
    "model": "DIN",
    "model_id": "DIN_tune_t001_s2026",
    "model_root": "/NAS/hyunwoong/Hayanmind-project/notebook/artifacts/runs",
    "monitor": "AUC",
    "monitor_mode": "max",
    "net_dropout": "0.0045884079965860525",
    "net_regularizer": "0",
    "num_workers": "3",
    "optimizer": "adam",
    "pickle_feature_encoder": "True",
    "save_best_only": "False",
    "seed": "2026",
    "shuffle": "True",
    "task": "binary_classification",
    "test_data": "/NAS/hyunwoong/Hayanmind-project/data/TAAC2026/test.parquet",
    "train_data": "/NAS/hyunwoong/Hayanmind-project/data/TAAC2026/train.parquet",
    "use_features": "None",
    "valid_data": "/NAS/hyunwoong/Hayanmind-project/data/TAAC2026/valid.parquet",
    "verbose": "1"
}
2026-04-19 15:29:29,240 P2399999 INFO Load feature_map from json: /NAS/hyunwoong/Hayanmind-project/data/TAAC2026/feature_map.json
2026-04-19 15:29:29,242 P2399999 INFO Set column index...
2026-04-19 15:29:29,244 P2399999 INFO Loading datasets...
2026-04-19 15:29:29,344 P2399999 INFO Train samples: total/630, blocks/1
2026-04-19 15:29:29,387 P2399999 INFO Validation samples: total/70, blocks/1
2026-04-19 15:29:29,389 P2399999 INFO Loading train and validation data done.
2026-04-19 15:29:29,786 P2399999 INFO Loading pretrained_emb: /NAS/hyunwoong/Hayanmind-project/data/TAAC2026/pretrained_fid_61.h5
2026-04-19 15:29:30,847 P2399999 INFO Loading pretrained_emb: /NAS/hyunwoong/Hayanmind-project/data/TAAC2026/pretrained_fid_87.h5
2026-04-19 15:29:32,474 P2399999 INFO Total number of parameters: 51076354.
2026-04-19 15:29:32,476 P2399999 INFO Start training: 1 batches/epoch
2026-04-19 15:29:32,477 P2399999 INFO ************ Epoch=1 start ************

  0%|          | 0/1 [00:00<?, ?it/s]

2026-04-19 15:29:32,748 P2399999 INFO Train loss: 12.222222
2026-04-19 15:29:32,751 P2399999 INFO Evaluation @epoch 1 - batch 1:

100%|██████████| 1/1 [00:00<00:00,  4.20it/s]

2026-04-19 15:29:33,013 P2399999 INFO [Metrics] AUC: 0.500000

100%|██████████| 1/1 [00:02<00:00,  2.49s/it]

2026-04-19 15:29:34,982 P2399999 INFO ************ Epoch=1 end ************

  0%|          | 0/1 [00:00<?, ?it/s]

2026-04-19 15:29:35,260 P2399999 INFO Train loss: 12.222222
2026-04-19 15:29:35,264 P2399999 INFO Evaluation @epoch 2 - batch 1:

100%|██████████| 1/1 [00:00<00:00,  3.76it/s]

2026-04-19 15:29:35,554 P2399999 INFO [Metrics] AUC: 0.500000
2026-04-19 15:29:35,560 P2399999 INFO Monitor(max)=0.500000 STOP!
2026-04-19 15:29:35,561 P2399999 INFO Reduce learning rate on plateau: 0.000078

100%|██████████| 1/1 [00:02<00:00,  2.59s/it]

2026-04-19 15:29:37,589 P2399999 INFO ************ Epoch=2 end ************

  0%|          | 0/1 [00:00<?, ?it/s]

2026-04-19 15:29:37,864 P2399999 INFO Train loss: 12.222222
2026-04-19 15:29:37,869 P2399999 INFO Evaluation @epoch 3 - batch 1:

100%|██████████| 1/1 [00:00<00:00,  3.83it/s]

2026-04-19 15:29:38,152 P2399999 INFO [Metrics] AUC: 0.500000
2026-04-19 15:29:38,157 P2399999 INFO Monitor(max)=0.500000 STOP!
2026-04-19 15:29:38,158 P2399999 INFO Reduce learning rate on plateau: 0.000008
2026-04-19 15:29:38,159 P2399999 INFO ********* Epoch=3 early stop *********

  0%|          | 0/1 [00:02<?, ?it/s]

2026-04-19 15:29:40,158 P2399999 INFO Training finished.
2026-04-19 15:29:40,160 P2399999 INFO Load best model: /NAS/hyunwoong/Hayanmind-project/notebook/artifacts/runs/TAAC2026/DIN_tune_t001_s2026.model

2026-04-19 15:29:42,011 P2399999 INFO *** Validation evaluation (run=tune_t001_s2026) ***

100%|██████████| 1/1 [00:00<00:00,  4.72it/s]

2026-04-19 15:29:42,239 P2399999 INFO [Metrics] AUC: 0.500000 - logloss: 2.302585
2026-04-19 15:29:42,245 P2399999 INFO *** Test evaluation (run=tune_t001_s2026) ***
2026-04-19 15:29:42,246 P2399999 INFO Loading datasets...
2026-04-19 15:29:42,338 P2399999 INFO Test samples: total/300, blocks/1
2026-04-19 15:29:42,340 P2399999 INFO Loading test data done.

100%|██████████| 1/1 [00:00<00:00,  3.87it/s]

2026-04-19 15:29:42,620 P2399999 INFO [Metrics] AUC: 0.500000 - logloss: 1.987899
[I 2026-04-19 15:29:42,677] Trial 1 finished with value: 0.5 and parameters: {'learning_rate': 0.000780037276846175, 'embedding_dim': 32, 'dnn_hidden_units': '[512, 256, 128]', 'net_dropout': 0.0045884079965860525, 'attention_dropout': 0.2533409855578874, 'batch_size': 4096}. Best is trial 0 with value: 0.5.

[run tune_t001_s2026] valid=OrderedDict([('AUC', 0.5), ('logloss', 2.302585178708335)])  test=OrderedDict([('AUC', 0.5), ('logloss', 1.9878985512848644)])
[run tune_t001_s2026] artifacts -> /NAS/hyunwoong/Hayanmind-project/notebook/artifacts/runs/TAAC2026/DIN_tune_t001_s2026.*
[trial 1] valid_AUC=0.50000  params={'learning_rate': 0.000780037276846175, 'embedding_dim': 32, 'dnn_hidden_units': [512, 256, 128], 'net_dropout': 0.0045884079965860525, 'attention_dropout': 0.2533409855578874, 'batch_size': 4096}

2026-04-19 15:29:42,807 P2399999 INFO FuxiCTR version: 2.3.9
2026-04-19 15:29:42,809 P2399999 INFO Run tune_t002_s2026: {
    "attention_dropout": "0.21761552589013844",
    "attention_hidden_activations": "Dice",
    "attention_hidden_units": "[64]",
    "attention_output_activation": "None",
    "batch_norm": "False",
    "batch_size": "8192",
    "data_format": "parquet",
    "data_root": "/NAS/hyunwoong/Hayanmind-project/data",
    "dataset_id": "TAAC2026",
    "debug_mode": "False",
    "din_sequence_field": "item_int_feats_11",
    "din_target_field": "item_id",
    "din_use_softmax": "False",
    "dnn_activations": "relu",
    "dnn_hidden_units": "[1024, 512, 256]",
    "early_stop_patience": "2",
    "embedding_dim": "32",
    "embedding_regularizer": "0",
    "epochs": "3",
    "eval_steps": "None",
    "feature_config": "None",
    "feature_specs": "[{'name': 'item_int_feats_11', 'feature_encoder': None}]",
    "gpu": "0",
    "group_id": "None",
    "learning_rate": "0.0009891936374539197",
    "loss": "binary_crossentropy",
    "metrics": "['AUC', 'logloss']",
    "model": "DIN",
    "model_id": "DIN_tune_t002_s2026",
    "model_root": "/NAS/hyunwoong/Hayanmind-project/notebook/artifacts/runs",
    "monitor": "AUC",
    "monitor_mode": "max",
    "net_dropout": "0.26968945788027004",
    "net_regularizer": "0",
    "num_workers": "3",
    "optimizer": "adam",
    "pickle_feature_encoder": "True",
    "save_best_only": "False",
    "seed": "2026",
    "shuffle": "True",
    "task": "binary_classification",
    "test_data": "/NAS/hyunwoong/Hayanmind-project/data/TAAC2026/test.parquet",
    "train_data": "/NAS/hyunwoong/Hayanmind-project/data/TAAC2026/train.parquet",
    "use_features": "None",
    "valid_data": "/NAS/hyunwoong/Hayanmind-project/data/TAAC2026/valid.parquet",
    "verbose": "1"
}
2026-04-19 15:29:42,812 P2399999 INFO Load feature_map from json: /NAS/hyunwoong/Hayanmind-project/data/TAAC2026/feature_map.json
2026-04-19 15:29:42,814 P2399999 INFO Set column index...
2026-04-19 15:29:42,816 P2399999 INFO Loading datasets...
2026-04-19 15:29:42,928 P2399999 INFO Train samples: total/630, blocks/1
2026-04-19 15:29:42,975 P2399999 INFO Validation samples: total/70, blocks/1
2026-04-19 15:29:42,977 P2399999 INFO Loading train and validation data done.
2026-04-19 15:29:43,375 P2399999 INFO Loading pretrained_emb: /NAS/hyunwoong/Hayanmind-project/data/TAAC2026/pretrained_fid_61.h5
2026-04-19 15:29:44,403 P2399999 INFO Loading pretrained_emb: /NAS/hyunwoong/Hayanmind-project/data/TAAC2026/pretrained_fid_87.h5
2026-04-19 15:29:46,020 P2399999 INFO Total number of parameters: 53502210.
2026-04-19 15:29:46,023 P2399999 INFO Start training: 1 batches/epoch
2026-04-19 15:29:46,025 P2399999 INFO ************ Epoch=1 start ************

  0%|          | 0/1 [00:00<?, ?it/s]

2026-04-19 15:29:46,321 P2399999 INFO Train loss: 87.777779
2026-04-19 15:29:46,325 P2399999 INFO Evaluation @epoch 1 - batch 1:

100%|██████████| 1/1 [00:00<00:00,  3.83it/s]

2026-04-19 15:29:46,610 P2399999 INFO [Metrics] AUC: 0.500000

100%|██████████| 1/1 [00:02<00:00,  2.57s/it]

2026-04-19 15:29:48,613 P2399999 INFO ************ Epoch=1 end ************

  0%|          | 0/1 [00:00<?, ?it/s]

2026-04-19 15:29:48,910 P2399999 INFO Train loss: 87.777779
2026-04-19 15:29:48,914 P2399999 INFO Evaluation @epoch 2 - batch 1:

100%|██████████| 1/1 [00:00<00:00,  3.91it/s]

2026-04-19 15:29:49,192 P2399999 INFO [Metrics] AUC: 0.500000
2026-04-19 15:29:49,196 P2399999 INFO Monitor(max)=0.500000 STOP!
2026-04-19 15:29:49,198 P2399999 INFO Reduce learning rate on plateau: 0.000099

100%|██████████| 1/1 [00:02<00:00,  2.76s/it]

2026-04-19 15:29:51,396 P2399999 INFO ************ Epoch=2 end ************

  0%|          | 0/1 [00:00<?, ?it/s]

2026-04-19 15:29:51,685 P2399999 INFO Train loss: 87.777779
2026-04-19 15:29:51,689 P2399999 INFO Evaluation @epoch 3 - batch 1:

100%|██████████| 1/1 [00:00<00:00,  3.74it/s]

2026-04-19 15:29:51,981 P2399999 INFO [Metrics] AUC: 0.500000
2026-04-19 15:29:51,986 P2399999 INFO Monitor(max)=0.500000 STOP!
2026-04-19 15:29:51,988 P2399999 INFO Reduce learning rate on plateau: 0.000010
2026-04-19 15:29:51,990 P2399999 INFO ********* Epoch=3 early stop *********

  0%|          | 0/1 [00:02<?, ?it/s]

2026-04-19 15:29:54,163 P2399999 INFO Training finished.
2026-04-19 15:29:54,164 P2399999 INFO Load best model: /NAS/hyunwoong/Hayanmind-project/notebook/artifacts/runs/TAAC2026/DIN_tune_t002_s2026.model

2026-04-19 15:29:56,084 P2399999 INFO *** Validation evaluation (run=tune_t002_s2026) ***

100%|██████████| 1/1 [00:00<00:00,  4.34it/s]

2026-04-19 15:29:56,336 P2399999 INFO [Metrics] AUC: 0.500000 - logloss: 13.815511
2026-04-19 15:29:56,343 P2399999 INFO *** Test evaluation (run=tune_t002_s2026) ***
2026-04-19 15:29:56,347 P2399999 INFO Loading datasets...
2026-04-19 15:29:56,424 P2399999 INFO Test samples: total/300, blocks/1
2026-04-19 15:29:56,425 P2399999 INFO Loading test data done.

100%|██████████| 1/1 [00:00<00:00,  5.92it/s]

2026-04-19 15:29:56,605 P2399999 INFO [Metrics] AUC: 0.500000 - logloss: 14.130197

[run tune_t002_s2026] valid=OrderedDict([('AUC', 0.5), ('logloss', 13.815510572701148)])  test=OrderedDict([('AUC', 0.5), ('logloss', 14.130197200134901)])
[run tune_t002_s2026] artifacts -> /NAS/hyunwoong/Hayanmind-project/notebook/artifacts/runs/TAAC2026/DIN_tune_t002_s2026.*
[trial 2] valid_AUC=0.50000  params={'learning_rate': 0.0009891936374539197, 'embedding_dim': 32, 'dnn_hidden_units': [1024, 512, 256], 'net_dropout': 0.26968945788027004, 'attention_dropout': 0.21761552589013844, 'batch_size': 8192}

[I 2026-04-19 15:29:56,674] Trial 2 finished with value: 0.5 and parameters: {'learning_rate': 0.0009891936374539197, 'embedding_dim': 32, 'dnn_hidden_units': '[1024, 512, 256]', 'net_dropout': 0.26968945788027004, 'attention_dropout': 0.21761552589013844, 'batch_size': 8192}. Best is trial 0 with value: 0.5.

=== Optuna summary ===
best value  = 0.5
best params = {'learning_rate': 0.0007604734065844932, 'embedding_dim': 32, 'dnn_hidden_units': '[512, 256, 128]', 'net_dropout': 0.04846728945740564, 'attention_dropout': 0.2150721079075201, 'batch_size': 4096}

,number,value,state,params_attention_dropout,params_batch_size,params_dnn_hidden_units,params_embedding_dim,params_learning_rate,params_net_dropout,datetime_complete
0,0,0.5,COMPLETE,0.215072,4096,"[512, 256, 128]",32,0.000760,0.048467,2026-04-19 15:29:29.056409
1,1,0.5,COMPLETE,0.253341,4096,"[512, 256, 128]",32,0.000780,0.004588,2026-04-19 15:29:42.662278
2,2,0.5,COMPLETE,0.217616,8192,"[1024, 512, 256]",32,0.000989,0.269689,2026-04-19 15:29:56.654861

## 4. best params로 최종 학습 (N_REPEATS)

seed만 다르게 `N_REPEATS`번 재학습한다. 이때는 `save_test_preds=True` 로
test 예측을 parquet에 저장 → 04 분석 노트북에서 바로 로드 가능.

In [6]:
final_summaries = []
for seed in SEEDS:
    params = copy.deepcopy(base_cfg)
    params.update(U.decode_best_params(study.best_params))
    params['seed'] = seed
    run_id = U.make_run_id(MODEL, DATASET_ID, seed)
    print(f'\n=== FINAL RUN seed={seed}  run_id={run_id} ===')
    summary = U.run_training(
        dataset_id=DATASET_ID,
        model_name=MODEL,
        params=params,
        run_id=run_id,
        save_test_preds=True,
    )
    final_summaries.append(summary)

final_df = pd.DataFrame(final_summaries)
print('\n=== final runs ===')
final_df

=== FINAL RUN seed=2026  run_id=20260419-152956_DIN_TAAC2026_s2026 ===

2026-04-19 15:29:56,802 P2399999 INFO FuxiCTR version: 2.3.9
2026-04-19 15:29:56,804 P2399999 INFO Run 20260419-152956_DIN_TAAC2026_s2026: {
    "attention_dropout": "0.2150721079075201",
    "attention_hidden_activations": "Dice",
    "attention_hidden_units": "[64]",
    "attention_output_activation": "None",
    "batch_norm": "False",
    "batch_size": "4096",
    "data_format": "parquet",
    "data_root": "/NAS/hyunwoong/Hayanmind-project/data",
    "dataset_id": "TAAC2026",
    "debug_mode": "False",
    "din_sequence_field": "item_int_feats_11",
    "din_target_field": "item_id",
    "din_use_softmax": "False",
    "dnn_activations": "relu",
    "dnn_hidden_units": "[512, 256, 128]",
    "early_stop_patience": "2",
    "embedding_dim": "32",
    "embedding_regularizer": "0",
    "epochs": "20",
    "eval_steps": "None",
    "feature_config": "None",
    "feature_specs": "[{'name': 'item_int_feats_11', 'feature_encoder': None}]",
    "gpu": "0",
    "group_id": "None",
    "learning_rate": "0.0007604734065844932",
    "loss": "binary_crossentropy",
    "metrics": "['AUC', 'logloss']",
    "model": "DIN",
    "model_id": "DIN_20260419-152956_DIN_TAAC2026_s2026",
    "model_root": "/NAS/hyunwoong/Hayanmind-project/notebook/artifacts/runs",
    "monitor": "AUC",
    "monitor_mode": "max",
    "net_dropout": "0.04846728945740564",
    "net_regularizer": "0",
    "num_workers": "3",
    "optimizer": "adam",
    "pickle_feature_encoder": "True",
    "save_best_only": "True",
    "seed": "2026",
    "shuffle": "True",
    "task": "binary_classification",
    "test_data": "/NAS/hyunwoong/Hayanmind-project/data/TAAC2026/test.parquet",
    "train_data": "/NAS/hyunwoong/Hayanmind-project/data/TAAC2026/train.parquet",
    "use_features": "None",
    "valid_data": "/NAS/hyunwoong/Hayanmind-project/data/TAAC2026/valid.parquet",
    "verbose": "1"
}
2026-04-19 15:29:56,808 P2399999 INFO Load feature_map from json: /NAS/hyunwoong/Hayanmind-project/data/TAAC2026/feature_map.json
2026-04-19 15:29:56,817 P2399999 INFO Set column index...
2026-04-19 15:29:56,819 P2399999 INFO Loading datasets...
2026-04-19 15:29:56,894 P2399999 INFO Train samples: total/630, blocks/1
2026-04-19 15:29:56,932 P2399999 INFO Validation samples: total/70, blocks/1
2026-04-19 15:29:56,934 P2399999 INFO Loading train and validation data done.
2026-04-19 15:29:57,278 P2399999 INFO Loading pretrained_emb: /NAS/hyunwoong/Hayanmind-project/data/TAAC2026/pretrained_fid_61.h5
2026-04-19 15:29:58,344 P2399999 INFO Loading pretrained_emb: /NAS/hyunwoong/Hayanmind-project/data/TAAC2026/pretrained_fid_87.h5
2026-04-19 15:30:00,142 P2399999 INFO Total number of parameters: 51076354.
2026-04-19 15:30:00,147 P2399999 INFO Start training: 1 batches/epoch
2026-04-19 15:30:00,148 P2399999 INFO ************ Epoch=1 start ************

  0%|          | 0/1 [00:00<?, ?it/s]

2026-04-19 15:30:00,323 P2399999 INFO Train loss: 13.809524
2026-04-19 15:30:00,326 P2399999 INFO Evaluation @epoch 1 - batch 1:

100%|██████████| 1/1 [00:00<00:00,  6.66it/s]

2026-04-19 15:30:00,485 P2399999 INFO [Metrics] AUC: 0.500000
2026-04-19 15:30:00,487 P2399999 INFO Save best model: monitor(max)=0.500000

100%|██████████| 1/1 [00:02<00:00,  2.25s/it]

2026-04-19 15:30:02,409 P2399999 INFO ************ Epoch=1 end ************

  0%|          | 0/1 [00:00<?, ?it/s]

2026-04-19 15:30:02,682 P2399999 INFO Train loss: 14.603175
2026-04-19 15:30:02,686 P2399999 INFO Evaluation @epoch 2 - batch 1:

100%|██████████| 1/1 [00:00<00:00,  3.92it/s]

2026-04-19 15:30:02,965 P2399999 INFO [Metrics] AUC: 0.500000
2026-04-19 15:30:02,969 P2399999 INFO Monitor(max)=0.500000 STOP!
2026-04-19 15:30:02,971 P2399999 INFO Reduce learning rate on plateau: 0.000076

100%|██████████| 1/1 [00:00<00:00,  1.60it/s]

2026-04-19 15:30:03,052 P2399999 INFO ************ Epoch=2 end ************

  0%|          | 0/1 [00:00<?, ?it/s]

2026-04-19 15:30:03,331 P2399999 INFO Train loss: 13.968254
2026-04-19 15:30:03,335 P2399999 INFO Evaluation @epoch 3 - batch 1:

100%|██████████| 1/1 [00:00<00:00,  3.89it/s]

2026-04-19 15:30:03,612 P2399999 INFO [Metrics] AUC: 0.500000
2026-04-19 15:30:03,617 P2399999 INFO Monitor(max)=0.500000 STOP!
2026-04-19 15:30:03,619 P2399999 INFO Reduce learning rate on plateau: 0.000008
2026-04-19 15:30:03,620 P2399999 INFO ********* Epoch=3 early stop *********

  0%|          | 0/1 [00:00<?, ?it/s]

2026-04-19 15:30:03,699 P2399999 INFO Training finished.
2026-04-19 15:30:03,700 P2399999 INFO Load best model: /NAS/hyunwoong/Hayanmind-project/notebook/artifacts/runs/TAAC2026/DIN_20260419-152956_DIN_TAAC2026_s2026.model

2026-04-19 15:30:05,523 P2399999 INFO *** Validation evaluation (run=20260419-152956_DIN_TAAC2026_s2026) ***

100%|██████████| 1/1 [00:00<00:00,  4.70it/s]

2026-04-19 15:30:05,755 P2399999 INFO [Metrics] AUC: 0.500000 - logloss: 2.302585
2026-04-19 15:30:05,760 P2399999 INFO *** Test evaluation (run=20260419-152956_DIN_TAAC2026_s2026) ***
2026-04-19 15:30:05,762 P2399999 INFO Loading datasets...
2026-04-19 15:30:05,854 P2399999 INFO Test samples: total/300, blocks/1
2026-04-19 15:30:05,856 P2399999 INFO Loading test data done.

100%|██████████| 1/1 [00:00<00:00,  3.66it/s]

2026-04-19 15:30:06,152 P2399999 INFO [Metrics] AUC: 0.500000 - logloss: 1.987899
2026-04-19 15:30:06,160 P2399999 INFO Loading datasets...
2026-04-19 15:30:06,237 P2399999 INFO Test samples: total/300, blocks/1
2026-04-19 15:30:06,239 P2399999 INFO Loading test data done.

100%|██████████| 1/1 [00:00<00:00,  3.85it/s]

2026-04-19 15:30:06,614 P2399999 INFO FuxiCTR version: 2.3.9
2026-04-19 15:30:06,615 P2399999 INFO Run 20260419-153006_DIN_TAAC2026_s2027: {
    "attention_dropout": "0.2150721079075201",
    "attention_hidden_activations": "Dice",
    "attention_hidden_units": "[64]",
    "attention_output_activation": "None",
    "batch_norm": "False",
    "batch_size": "4096",
    "data_format": "parquet",
    "data_root": "/NAS/hyunwoong/Hayanmind-project/data",
    "dataset_id": "TAAC2026",
    "debug_mode": "False",
    "din_sequence_field": "item_int_feats_11",
    "din_target_field": "item_id",
    "din_use_softmax": "False",
    "dnn_activations": "relu",
    "dnn_hidden_units": "[512, 256, 128]",
    "early_stop_patience": "2",
    "embedding_dim": "32",
    "embedding_regularizer": "0",
    "epochs": "20",
    "eval_steps": "None",
    "feature_config": "None",
    "feature_specs": "[{'name': 'item_int_feats_11', 'feature_encoder': None}]",
    "gpu": "0",
    "group_id": "None",
    "learning_rate": "0.0007604734065844932",
    "loss": "binary_crossentropy",
    "metrics": "['AUC', 'logloss']",
    "model": "DIN",
    "model_id": "DIN_20260419-153006_DIN_TAAC2026_s2027",
    "model_root": "/NAS/hyunwoong/Hayanmind-project/notebook/artifacts/runs",
    "monitor": "AUC",
    "monitor_mode": "max",
    "net_dropout": "0.04846728945740564",
    "net_regularizer": "0",
    "num_workers": "3",
    "optimizer": "adam",
    "pickle_feature_encoder": "True",
    "save_best_only": "True",
    "seed": "2027",
    "shuffle": "True",
    "task": "binary_classification",
    "test_data": "/NAS/hyunwoong/Hayanmind-project/data/TAAC2026/test.parquet",
    "train_data": "/NAS/hyunwoong/Hayanmind-project/data/TAAC2026/train.parquet",
    "use_features": "None",
    "valid_data": "/NAS/hyunwoong/Hayanmind-project/data/TAAC2026/valid.parquet",
    "verbose": "1"
}
2026-04-19 15:30:06,618 P2399999 INFO Load feature_map from json: /NAS/hyunwoong/Hayanmind-project/data/TAAC2026/feature_map.json
2026-04-19 15:30:06,621 P2399999 INFO Set column index...
2026-04-19 15:30:06,622 P2399999 INFO Loading datasets...

[preds] saved 300 rows -> /NAS/hyunwoong/Hayanmind-project/notebook/artifacts/predictions/TAAC2026/DIN/20260419-152956_DIN_TAAC2026_s2026/preds.parquet
[run 20260419-152956_DIN_TAAC2026_s2026] valid=OrderedDict([('AUC', 0.5), ('logloss', 2.302585178708335)])  test=OrderedDict([('AUC', 0.5), ('logloss', 1.9878985512848644)])
[run 20260419-152956_DIN_TAAC2026_s2026] artifacts -> /NAS/hyunwoong/Hayanmind-project/notebook/artifacts/runs/TAAC2026/DIN_20260419-152956_DIN_TAAC2026_s2026.*
[run 20260419-152956_DIN_TAAC2026_s2026] preds    -> /NAS/hyunwoong/Hayanmind-project/notebook/artifacts/predictions/TAAC2026/DIN/20260419-152956_DIN_TAAC2026_s2026/preds.parquet

=== FINAL RUN seed=2027  run_id=20260419-153006_DIN_TAAC2026_s2027 ===

2026-04-19 15:30:06,725 P2399999 INFO Train samples: total/630, blocks/1
2026-04-19 15:30:06,767 P2399999 INFO Validation samples: total/70, blocks/1
2026-04-19 15:30:06,769 P2399999 INFO Loading train and validation data done.
2026-04-19 15:30:07,161 P2399999 INFO Loading pretrained_emb: /NAS/hyunwoong/Hayanmind-project/data/TAAC2026/pretrained_fid_61.h5
2026-04-19 15:30:08,224 P2399999 INFO Loading pretrained_emb: /NAS/hyunwoong/Hayanmind-project/data/TAAC2026/pretrained_fid_87.h5
2026-04-19 15:30:09,914 P2399999 INFO Total number of parameters: 51076354.
2026-04-19 15:30:09,916 P2399999 INFO Start training: 1 batches/epoch
2026-04-19 15:30:09,918 P2399999 INFO ************ Epoch=1 start ************

  0%|          | 0/1 [00:00<?, ?it/s]

2026-04-19 15:30:10,184 P2399999 INFO Train loss: 14.920635
2026-04-19 15:30:10,189 P2399999 INFO Evaluation @epoch 1 - batch 1:

100%|██████████| 1/1 [00:00<00:00,  3.64it/s]

2026-04-19 15:30:10,485 P2399999 INFO [Metrics] AUC: 0.500000
2026-04-19 15:30:10,490 P2399999 INFO Save best model: monitor(max)=0.500000

100%|██████████| 1/1 [00:02<00:00,  2.47s/it]

2026-04-19 15:30:12,407 P2399999 INFO ************ Epoch=1 end ************

  0%|          | 0/1 [00:00<?, ?it/s]

2026-04-19 15:30:12,713 P2399999 INFO Train loss: 14.761905
2026-04-19 15:30:12,719 P2399999 INFO Evaluation @epoch 2 - batch 1:

100%|██████████| 1/1 [00:00<00:00,  3.78it/s]

2026-04-19 15:30:13,008 P2399999 INFO [Metrics] AUC: 0.500000
2026-04-19 15:30:13,012 P2399999 INFO Monitor(max)=0.500000 STOP!
2026-04-19 15:30:13,014 P2399999 INFO Reduce learning rate on plateau: 0.000076

100%|██████████| 1/1 [00:00<00:00,  1.49it/s]

2026-04-19 15:30:13,099 P2399999 INFO ************ Epoch=2 end ************

  0%|          | 0/1 [00:00<?, ?it/s]

2026-04-19 15:30:13,388 P2399999 INFO Train loss: 13.492064
2026-04-19 15:30:13,392 P2399999 INFO Evaluation @epoch 3 - batch 1:

100%|██████████| 1/1 [00:00<00:00,  3.83it/s]

2026-04-19 15:30:13,673 P2399999 INFO [Metrics] AUC: 0.500000
2026-04-19 15:30:13,678 P2399999 INFO Monitor(max)=0.500000 STOP!
2026-04-19 15:30:13,680 P2399999 INFO Reduce learning rate on plateau: 0.000008
2026-04-19 15:30:13,681 P2399999 INFO ********* Epoch=3 early stop *********

  0%|          | 0/1 [00:00<?, ?it/s]

2026-04-19 15:30:13,762 P2399999 INFO Training finished.
2026-04-19 15:30:13,764 P2399999 INFO Load best model: /NAS/hyunwoong/Hayanmind-project/notebook/artifacts/runs/TAAC2026/DIN_20260419-153006_DIN_TAAC2026_s2027.model

2026-04-19 15:30:15,596 P2399999 INFO *** Validation evaluation (run=20260419-153006_DIN_TAAC2026_s2027) ***

100%|██████████| 1/1 [00:00<00:00,  4.42it/s]

2026-04-19 15:30:15,840 P2399999 INFO [Metrics] AUC: 0.500000 - logloss: 2.302585
2026-04-19 15:30:15,844 P2399999 INFO *** Test evaluation (run=20260419-153006_DIN_TAAC2026_s2027) ***
2026-04-19 15:30:15,846 P2399999 INFO Loading datasets...
2026-04-19 15:30:15,929 P2399999 INFO Test samples: total/300, blocks/1
2026-04-19 15:30:15,930 P2399999 INFO Loading test data done.

100%|██████████| 1/1 [00:00<00:00,  3.74it/s]

2026-04-19 15:30:16,220 P2399999 INFO [Metrics] AUC: 0.500000 - logloss: 1.987899
2026-04-19 15:30:16,227 P2399999 INFO Loading datasets...
2026-04-19 15:30:16,303 P2399999 INFO Test samples: total/300, blocks/1
2026-04-19 15:30:16,304 P2399999 INFO Loading test data done.

100%|██████████| 1/1 [00:00<00:00,  3.66it/s]
[preds] saved 300 rows -> /NAS/hyunwoong/Hayanmind-project/notebook/artifacts/predictions/TAAC2026/DIN/20260419-153006_DIN_TAAC2026_s2027/preds.parquet
[run 20260419-153006_DIN_TAAC2026_s2027] valid=OrderedDict([('AUC', 0.5), ('logloss', 2.302585178708335)])  test=OrderedDict([('AUC', 0.5), ('logloss', 1.9878985512848644)])
[run 20260419-153006_DIN_TAAC2026_s2027] artifacts -> /NAS/hyunwoong/Hayanmind-project/notebook/artifacts/runs/TAAC2026/DIN_20260419-153006_DIN_TAAC2026_s2027.*
[run 20260419-153006_DIN_TAAC2026_s2027] preds    -> /NAS/hyunwoong/Hayanmind-project/notebook/artifacts/predictions/TAAC2026/DIN/20260419-153006_DIN_TAAC2026_s2027/preds.parquet

=== final runs ===

,model,dataset_id,run_id,model_id,train_seconds,valid_AUC,valid_logloss,test_AUC,test_logloss
0,DIN,TAAC2026,20260419-152956_DIN_TAAC2026_s2026,DIN_20260419-152956_DIN_TAAC2026_s2026,5.38,0.5,2.302585,0.5,1.987899
1,DIN,TAAC2026,20260419-153006_DIN_TAAC2026_s2027,DIN_20260419-153006_DIN_TAAC2026_s2027,5.68,0.5,2.302585,0.5,1.987899

## 5. 저장된 run 요약 출력 (list_runs)

`artifacts/runs/{DATASET_ID}/` 아래에 쌓인 모든 run(튜닝 trial 포함)을 메트릭 표로.

In [7]:
runs = U.list_runs(DATASET_ID)
cols = [c for c in ['dataset','model','run_id','metric.valid_AUC','metric.test_AUC','metric.valid_logloss','metric.test_logloss','metric.train_seconds'] if c in runs.columns]
runs[cols].sort_values(cols[-2] if 'metric.test_AUC' in cols else 'run_id', ascending=False).head(30)

,dataset,model,run_id,metric.valid_AUC,metric.test_AUC,metric.valid_logloss,metric.test_logloss,metric.train_seconds
4,TAAC2026,DIN,tune_t002_s2026,0.5,0.5,13.815511,14.130197,10.06
0,TAAC2026,DIN,20260419-152956_DIN_TAAC2026_s2026,0.5,0.5,2.302585,1.987899,5.38
1,TAAC2026,DIN,20260419-153006_DIN_TAAC2026_s2027,0.5,0.5,2.302585,1.987899,5.68
2,TAAC2026,DIN,tune_t000_s2026,0.5,0.5,2.302585,1.987899,9.79
3,TAAC2026,DIN,tune_t001_s2026,0.5,0.5,2.302585,1.987899,9.53